name: shop_app_clean_architecture
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2


  flutter_bloc: ^8.1.0
  bloc: ^8.0.3
  dio: ^4.0.5
  flutter_styled_toast: ^2.1.2+1
  shared_preferences: ^2.0.14
  carousel_slider: ^4.1.0
  cached_network_image: ^3.2.2


  flutter_staggered_animations: ^1.0.0
  google_fonts: ^4.0.3
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  flutter_screenutil: ^5.7.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/smart_shop.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/smart_shop.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/smart_shop.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/smart_shop.jpg"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/


